version: 2

sources:
  - name: data_source
    database: ANALYTICS_ENGINEER_TEST
    schema: DATA_SOURCE
    tables:
      - name: products
        description: "Product availability by country and date."
        columns:
          - name: product_id
            tests:
              - not_null
          - name: date
            tests:
              - not_null
      - name: countries
        description: "Reference table of countries."
        columns:
          - name: country_code
            tests:
              - not_null
              - unique